name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          echo "Hello, GitHub Actions!"
          echo "This is an example workflow."
          echo "You can add your own tasks here."
